using Manager.Models;

namespace Manager.Factories;

public class CitaFactory {
    
    /// <summary> Semilla de datos iniciales </summary>
    /// <returns>Citas iniciales</returns>
    public static IEnumerable<Cita> Seed() {
        var hoy = DateTime.Today;
        var ahora = DateTime.Now;
        return new List<Cita> {
            
            // borradas
            new() { Id = 1, Matricula = "1001-nhg", Marca = "Toyota", Modelo = "Corolla", Cilindrada = 1800, Motor = Cita.TiposMotor.Hibrido, Dni = "71625344D", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(1), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 2, Matricula = "1002-BBB", Marca = "BMW", Modelo = "M3", Cilindrada = 3000, Motor = Cita.TiposMotor.Gasolina, Dni = "22226666H", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(2), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 3, Matricula = "1003-CCC", Marca = "Tesla", Modelo = "Model 3", Cilindrada = 10, Motor = Cita.TiposMotor.Electrico, Dni = "88884444R", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(3), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 4, Matricula = "1004-DDD", Marca = "Audi", Modelo = "A3", Cilindrada = 2000, Motor = Cita.TiposMotor.Diesel, Dni = "10203040X", FechaMatriculacion = hoy.AddYears(-5), FechaInspeccion = DateTime.UtcNow.AddDays(4), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 5, Matricula = "1005-lmn", Marca = "Seat", Modelo = "Leon", Cilindrada = 1500, Motor = Cita.TiposMotor.Gasolina, Dni = "50403020S", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(5), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 6, Matricula = "1006-FFF", Marca = "Ford", Modelo = "Focus", Cilindrada = 1600, Motor = Cita.TiposMotor.Diesel, Dni = "96385274W", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(6), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new() { Id = 7, Matricula = "1007-GGG", Marca = "Mercedes", Modelo = "Clase A", Cilindrada = 2000, Motor = Cita.TiposMotor.Diesel, Dni = "14725836V", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(6), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 8, Matricula = "1008-HHH", Marca = "Hyundai", Modelo = "Tucson", Cilindrada = 1600, Motor = Cita.TiposMotor.Hibrido, Dni = "36925814G", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(7), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 9, Matricula = "1021-dbv", Marca = "Toyota", Modelo = "Yaris", Cilindrada = 1500, Motor = Cita.TiposMotor.Hibrido, Dni = "85214796A", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(8), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 10, Matricula = "1022-hVV", Marca = "BMW", Modelo = "X1", Cilindrada = 2000, Motor = Cita.TiposMotor.Diesel, Dni = "54712369S", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(9), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 11, Matricula = "1023-hWW", Marca = "Tesla", Modelo = "Model Y", Cilindrada = 500, Motor = Cita.TiposMotor.Electrico, Dni = "12398745C", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(10), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 12, Matricula = "1024-jXX", Marca = "Audi", Modelo = "Q3", Cilindrada = 2000, Motor = Cita.TiposMotor.Gasolina, Dni = "60606060W", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(11), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 13, Matricula = "1025-lYY", Marca = "Seat", Modelo = "Ateca", Cilindrada = 1600, Motor = Cita.TiposMotor.Diesel, Dni = "45454545J", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(12), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 14, Matricula = "1026-bZZ", Marca = "Ford", Modelo = "Kuga", Cilindrada = 2500, Motor = Cita.TiposMotor.Hibrido, Dni = "78787878K", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(13), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 15, Matricula = "1027-kpl", Marca = "Mercedes", Modelo = "GLC", Cilindrada = 2200, Motor = Cita.TiposMotor.Diesel, Dni = "12121212M", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(16), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 16, Matricula = "1028-BBB", Marca = "Hyundai", Modelo = "Ioniq", Cilindrada = 2000, Motor = Cita.TiposMotor.Electrico, Dni = "02468135M", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(20), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 17, Matricula = "1029-CCC", Marca = "Kia", Modelo = "Niro", Cilindrada = 1600, Motor = Cita.TiposMotor.Hibrido, Dni = "77777777B", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(25), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 18, Matricula = "1030-DDD", Marca = "Nissan", Modelo = "Juke", Cilindrada = 1000, Motor = Cita.TiposMotor.Gasolina, Dni = "33333333P", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(30), IsDeleted = true, CreatedAt = ahora, UpdatedAt = ahora },
            
            // no borradas
            new () { Id = 19, Matricula = "2041-bbb", Marca = "Renault", Modelo = "Clio", Cilindrada = 1200, Motor = Cita.TiposMotor.Gasolina, Dni = "12345678Z", FechaMatriculacion = hoy.AddYears(-6), FechaInspeccion = DateTime.UtcNow.AddDays(19), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 20, Matricula = "2042-BBB", Marca = "Peugeot", Modelo = "208", Cilindrada = 1400, Motor = Cita.TiposMotor.Diesel, Dni = "87654321X", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(6), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 21, Matricula = "2043-CCC", Marca = "Kia", Modelo = "Ceed", Cilindrada = 1600, Motor = Cita.TiposMotor.Hibrido, Dni = "23456789D", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(20), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 22, Matricula = "2044-DDD", Marca = "Hyundai", Modelo = "i30", Cilindrada = 1500, Motor = Cita.TiposMotor.Gasolina, Dni = "98765432M", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(23), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 23, Matricula = "2045-jnb", Marca = "Mazda", Modelo = "3", Cilindrada = 2000, Motor = Cita.TiposMotor.Gasolina, Dni = "34567890v", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(29), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 24, Matricula = "2046-FFF", Marca = "Nissan", Modelo = "Leaf", Cilindrada = 100, Motor = Cita.TiposMotor.Electrico, Dni = "01234567L", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(25), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 25, Matricula = "2047-GGG", Marca = "Volvo", Modelo = "XC40", Cilindrada = 1500, Motor = Cita.TiposMotor.Hibrido, Dni = "45678901G", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(27), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 26, Matricula = "2048-HHH", Marca = "Skoda", Modelo = "Fabia", Cilindrada = 1000, Motor = Cita.TiposMotor.Gasolina, Dni = "56789012B", FechaMatriculacion = hoy.AddYears(-5), FechaInspeccion = DateTime.UtcNow.AddDays(29), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 27, Matricula = "2049-kmm", Marca = "Fiat", Modelo = "500", Cilindrada = 100, Motor = Cita.TiposMotor.Electrico, Dni = "67890123B", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(27), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 28, Matricula = "2050-JJJ", Marca = "Opel", Modelo = "Corsa", Cilindrada = 1200, Motor = Cita.TiposMotor.Gasolina, Dni = "78901234X", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(6), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 29, Matricula = "3051-dff", Marca = "Porsche", Modelo = "Taycan", Cilindrada = 100, Motor = Cita.TiposMotor.Electrico, Dni = "11223344B", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(4), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 30, Matricula = "3052-BBB", Marca = "Mercedes", Modelo = "Clase C", Cilindrada = 2000, Motor = Cita.TiposMotor.Diesel, Dni = "55667788Z", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(1), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 31, Matricula = "3053-CCC", Marca = "Audi", Modelo = "A4", Cilindrada = 2000, Motor = Cita.TiposMotor.Gasolina, Dni = "99887766P", FechaMatriculacion = hoy.AddYears(-4), FechaInspeccion = DateTime.UtcNow.AddDays(1), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 32, Matricula = "3054-dwc", Marca = "Toyota", Modelo = "Prius", Cilindrada = 1800, Motor = Cita.TiposMotor.Hibrido, Dni = "44332211X", FechaMatriculacion = hoy.AddYears(-5), FechaInspeccion = DateTime.UtcNow.AddDays(2), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 33, Matricula = "3055-gfs", Marca = "BMW", Modelo = "iX", Cilindrada = 150, Motor = Cita.TiposMotor.Electrico, Dni = "13579246T", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(12), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 34, Matricula = "3056-FFF", Marca = "Seat", Modelo = "Tarraco", Cilindrada = 2000, Motor = Cita.TiposMotor.Diesel, Dni = "98712345W", FechaMatriculacion = hoy.AddYears(-2), FechaInspeccion = DateTime.UtcNow.AddDays(11), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 35, Matricula = "3057-GGG", Marca = "Ford", Modelo = "Mustang", Cilindrada = 5000, Motor = Cita.TiposMotor.Gasolina, Dni = "98712345W", FechaMatriculacion = hoy.AddYears(-3), FechaInspeccion = DateTime.UtcNow.AddDays(10), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora },
            new () { Id = 36, Matricula = "3058-HHH", Marca = "Hyundai", Modelo = "Ioniq 5", Cilindrada = 2000, Motor = Cita.TiposMotor.Electrico, Dni = "98712345W", FechaMatriculacion = hoy.AddYears(-1), FechaInspeccion = DateTime.UtcNow.AddDays(20), IsDeleted = false, CreatedAt = ahora, UpdatedAt = ahora }
        };
    }
}