<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ApplicationIcon>Images\app-icon.ico</ApplicationIcon>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.2.0"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0"/>
        
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.7" />

        <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.6" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.6" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
        
        <PackageReference Include="Dapper" Version="2.1.72"/>
        
        <PackageReference Include="Select.HtmlToPdf.NetCore" Version="25.2.0"/>

        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1"/>
    </ItemGroup>
    
    <ItemGroup>
      <Page Update="Views\Main\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>